### ISSUE TITLE
settings icon bug 

### ISSUE THREAD

**Issue by skruglov2023** [bocajthomas/SE-Extended#132] opened 2024-09-13 03:03 UTC
### Description

Probably an upstream SE problem, but I can't open SE-extended settings while in snapchat from the friend-feed settings gear. It appears to stop working from debugs around a month ago. 
Not the biggest problem but it does force me to open the SE-Extended app separately to check config. 

~~Also adding this under the same issue: SE-Extended (and SE) automatically are setting the auto-purge for messages to 3 days. I keep resetting it to Never, but it keeps resetting. My only workaround for now is to save the file every 3 days.~~

### Reproduction steps

1. Click the settings gear
2. SE does not show up. 

### Snapchat Version

v12.79.0.37

### SE Extended Version

[V1.0.0 814f759](https://github.com/bocajthomas/SE-Extended/commit/814f759dcf1d424e9290752ac897105462823109)

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment] 2024-09-13 10:14
Can you try update Snapchat, your using a very old version

Latest stable: v13.6.0.39

**Comment by skruglov2023** [comment] 2024-09-13 17:06
[SE Extended-logs-1726247091448.zip](https://github.com/user-attachments/files/16997256/SE.Extended-logs-1726247091448.zip)

**Comment by skruglov2023** [comment] 2024-09-13 17:41
I just got the latest snapchat to install, and both problems seem to be as they were before. Still can't open settings while in-app, and purge resets to 3 days automatically. 
Is it possible to just make a debug build that will have that set to Never by default?

**Comment by TheCodingCarson** [comment] 2024-09-19 02:31
Can confirm I have the same issue with the most recent official snapchat (from Google Play Store) and using lspatch.jar (on Windows) to patch the [dev build](https://github.com/bocajthomas/SE-Extended/actions/runs/10879209234) Core.apk into appmirror download of Snapchat v12.70.0.34 and using that [dev builds](https://github.com/bocajthomas/SE-Extended/actions/runs/10879209234) SE Extended to manage it.

**Comment by bocajthomas** [comment] 2024-09-19 12:39
### Settings Icon
- Its most likely caused by rhunk ( upstream dev ) trying to make the settings icon compatible with `Simple Snapchat`, Known issue

### Auto Purge
- I cant reproduce this bug. It looks like your an older debug ci, please update to the latest ci build.

**Comment by skruglov2023** [comment] 2024-09-20 02:16
I'm on the latest debug ci, from 3 days ago. Attached logs
[SE Extended-logs-1726798518088.zip](https://github.com/user-attachments/files/17068971/SE.Extended-logs-1726798518088.zip)

**Comment by bocajthomas** [comment] 2024-09-20 02:57
> I cleared logs, set purge back to never, restarted snap & SE, went into a conversation, closed both (swiped from recent apps), and then opened SE again to find the message purge back at 3 days. I have exported config recently with "never" selected, so I'm not sure how it just magically resets back to 3 days.

Did you press the back button before closing SE Extended?  

Example:
Press `Message Logger` then press `Auto Purge` then press `never` then press the back key on your navigation bar. 

When you select it and the dialog is still open then you close SE Extended it doesn't save the settings you need to press your back key.

**Comment by bocajthomas** [comment] 2024-09-20 03:10
Auto Purge is fixed 76e6817

**Comment by skruglov2023** [comment] 2024-09-20 04:53
Seems to be fixed, I'll update if it happens again in the next few days. Thanks!

**Closed** 2024-09-21 00:38 UTC
Labels: Issue Accepted, Low Priority
